### ISSUE TITLE
Can the travis berfore_install be made conditional on board?

### ISSUE THREAD

**Issue by wilberforce** [espruino/EspruinoBuildTools#2]
@gfwilliams 
It seems the way the matrix is applied all of this is brought in for all builds when not necessary:
```
 - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
 - sudo apt-get update
 - sudo apt-get install libsdl1.2-dev gcc-arm-embedded
 - curl -Ls http://s3.voneicken.com/xtensa-lx106-elf-20160330.tgx | tar Jxf -
 - curl -Ls http://s3.voneicken.com/esp_iot_sdk_v2.0.0.p1.tgx | tar Jxf -
 - curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp32/deploy/app.tgz | tar xfz -
 - curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp32/deploy/esp-idf.tgz | tar xfz -
 - curl -Ls https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz | tar xfz -
```

The worst offender is:
https://travis-ci.org/espruino/Espruino/jobs/206521630#L318

`sudo apt-get install libsdl1.2-dev gcc-arm-embedded`  192 secs

What I'm not sure about is if this before section is saved between each of the build jobs?

https://travis-ci.org/espruino/Espruino/builds/206521620

**Comment by gfwilliams** [comment]
Yes, I think it is all brought in fresh each time.

That was my reasoning for having a separate `provision.sh` script. You could have done `provision.sh $TARGET` (or whatever it was) to prepare for just that board.

I guess one easyish method would be to add something to the Makefile where you could set `INSTALL_TOOLS=1` and it'd automatically install the tools needed for compilation?

**Comment by gfwilliams** [comment]
I guess effectively in each section of the Makefile you'd have something like:

```
ifdef ESP8266
ifdef INSTALL_TOOLS
targets/esp8266/provision.sh
endif
...
```

**Comment by wilberforce** [comment]
The other way of doing it would be in the Travis script - in the before install, look at the board in the `env` and only pull in what was relevant to the board?

**Comment by gfwilliams** [comment]
Yes, it would be - but then we miss out on a way of making it much easier for normal users to get started?

Also, like I said before - it's all duplicated for Vagrant and Docker as well, so it'd be nice to take a step towards removing that duplication.

**Comment by wilberforce** [comment]
There is another Hicup for the installing for users case - and that is the toolchain is host operating system dependent. For Travis we can rely on 64bit Linux. Perhaps it would be best just to run with that for now.

Perhaps this would be a good time to split the Makefile into board targets - I'm not sure on how to go about this.

**Comment by wilberforce** [comment]
It looks like the apt sources can be cached:

https://atchai.com/blog/faster-ci/

```
cache:
    apt: true

addons:
    apt:
        sources:
            - elasticsearch-1.7
        packages:
            - elasticsearch
            - libpq-dev
            - libevent-dev
            - libxml2-dev
            - libxslt1-dev
            - python-dev
```

There is an existing pull request to add the official arm toolchain - looks like no one at Travis is listening...
https://github.com/travis-ci/apt-source-whitelist/pull/219

**Comment by gfwilliams** [comment]
Sigh, that's a shame.

I think 64 bit linux is fine - if someone wants to change it for other OSes later it'd be nice but it's not the end of the world having to run a VM.

**Comment by wilberforce** [comment]
Look at using multiple vars in the setup:

```
env:
  matrix:
    - BROWSER='chrome_linux'    BUILD='default'
    - BROWSER='chrome_linux'    BUILD='compat'
    - BROWSER='chrome_linux'    BUILD='nocompat'
```
    
then can add ARCH='arm' default and override for esp32, esp8266 and Linux

**Comment by wilberforce** [comment]
Scripts in Travis for arm tools setup:
https://github.com/BrewPi/firmware/blob/master/ci/install_arm_gcc.sh

https://github.com/BrewPi/firmware/blob/master/.travis.yml

```
install:
- ./ci/install_arm_gcc.sh
- ./platform/spark/firmware/ci/install_gcc.sh
- source ./ci/install_boost.sh
```

**Comment by wilberforce** [comment]
@gfwilliams 
I started this and didn't realise there was a `/scripts/provision.sh` used for vagrant, so might need to rename.

Not tested full yet...

Take a look anyway. I thought a common file that could be called from travis or the Makefile to provision for the first time, or if the prerequisites exists, just sets up the `env`

https://github.com/wilberforce/Espruino/blob/ESP32/scripts/provision.sh

**Comment by wilberforce** [comment]
https://github.com/espruino/EspruinoBuildTools/pull/3
