### ISSUE TITLE
sdkconfig missing

### ISSUE THREAD

**Issue by jumjum123** [espruino/EspruinoBuildTools#5]
Installed EspruinoBuildTools following README
It took a very long time to install gcc, about 10 minutes.
Once this was done compiling started and at the end I got this error:
**fatal error: sdkconfig.h: No such file or directory
compilation terminated.**

**Comment by jdschuitemaker** [comment]
Followed the same steps as @jumjum123 from the README and I am too seeing (multiple) fatal errors with regard to sdkconfig.h.

Other things I saw:
- bash: type: xtensa-esp32-elf-gcc: not found
- many warnings about 'conversion to', for example: warning: conversion to 'uint16_t {aka short unsigned int}' from 'int' may alter its value [-Wconversion]
- fatal error: ctype.h: No such file or directory

I have attached a complete log
[buildlog.txt](https://github.com/espruino/EspruinoBuildTools/files/885440/buildlog.txt)

**Comment by wilberforce** [comment]
@jumjum123 @jdschuitemaker 

Hi , i've updated to esp-idf 2.0 rc1

You will need to git pull in the EspruinoBuildTools and the Espruino sub folder.

If that does not work, please delete and re-pull.

If I get a chance tomorrow I will update to RC2.


There is a new partitions_espruino.csv and partitions_espruino.bin which defines how the flash is getting used.

This will be used for ota updates later...

**Comment by jdschuitemaker** [comment]
I did a re-pull and now I am seeing this:

`mconf.c:11:19: fatal error: ctype.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'mconf.o' failed
make[1]: *** [mconf.o] Error 1
make[1]: Leaving directory '/home/jan-dirk/EspruinoBuildTools/esp32/build/esp-idf/tools/kconfig'
tar: Removing leading `../' from member names
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
Makefile:21: recipe for target 'app.tgz' failed
make: *** [app.tgz] Error 2
ESP32`

And still a lot of warnings like the one below

`libs/compression/heatshrink/heatshrink_encoder.c:152:22: warning: conversion to 'uint16_t {aka short unsigned int}' from 'size_t {aka unsigned int}' may alter its value [-Wconversion]
     uint16_t cp_sz = rem < size ? rem : size;
`

**Comment by wilberforce** [comment]
@jdschuitemaker 

The warnings on conversion are normal, so can be ignored.

I think the best thing to do at this stage is to start again - it is very hard to diagnose what is going wrong.

Infact, you don't *need* to build this repository. It is used to produce the esp-idf components and save them so they can be used by the travis build.

If you do this:

```
git clone https://github.com/espruino/Espruino.git
cd Espruino
source ./Espruino/scripts/provision.sh ESP32
make clean && BOARD=ESP32 make 
```

It will install the tool chain and libraries.

**Comment by wilberforce** [comment]
@jumjum123 

These docs are really out of date and will confuse people:

https://github.com/espruino/Espruino/blob/master/targets/esp32/docs/README.md

Now it can be built with:

```
git clone https://github.com/espruino/Espruino.git
cd Espruino
source ./Espruino/scripts/provision.sh ESP32
make clean && BOARD=ESP32 make 
```

This does assume as 64 bit linux build so there will need to be some mention of how to build for Mac etc.

**Comment by jdschuitemaker** [comment]
I am getting closer but not yet there. I get this error now:

make/sanitycheck.make:24: *** You now need to build with 'BOARD=ESP32 make'.  Stop.

What am I supposed to do exactly? Linux noob here

**Comment by wilberforce** [comment]
Ah. I think you have an env var `ESP32=1`

`unset ESP32`

You night haven't in a script you'll need to remove it from there as well.

**Comment by jdschuitemaker** [comment]
You were correct about that. I guess I missed another step. I am now seeing
this:

make: xtensa-esp32-elf-gcc: Command not found
Makefile:740: recipe for target
'libs/compression/heatshrink/heatshrink_encoder.o' failed
make: *** [libs/compression/heatshrink/heatshrink_encoder.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.

thank you for all support!

Met vriendelijke groeten, Warm regards,

Jan-Dirk Schuitemaker

**Comment by wilberforce** [comment]
> make: xtensa-esp32-elf-gcc: Command not found

Sorry this step was missing, from the Espruino folder:

```
source ./Espruino/scripts/provision.sh ESP32
make clean && make
```

**Comment by jdschuitemaker** [comment]
Thank you again!

The first command was incorrect, I changed it to: source
~/Espruino/scripts/provision.sh ESP32

Next I ran "make clean && make", but I am seeing this error again:

CC libs/compression/heatshrink/heatshrink_encoder.o
libs/compression/heatshrink/heatshrink_encoder.c:1:20: fatal error:
stdlib.h: No such file or directory
compilation terminated.
Makefile:740: recipe for target
'libs/compression/heatshrink/heatshrink_encoder.o' failed
make: *** [libs/compression/heatshrink/heatshrink_encoder.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.

I found it from another location on my computer, but then followed more .h
files that were missing... Before finding them all on this machine I
thought it is better to ask why they are missing.

machine/ieeefp.h
_ansi.h

Thank again Wilberforce




Met vriendelijke groeten, Warm regards,

Jan-Dirk Schuitemaker

**Comment by wilberforce** [comment]
If you modify the script , it's not going to work!

For the source command to work the working folder should have been the Espruino folder, as the paths get set in the script and the folder is wrong, it won't set the correct path, and the includes can't be found.

I'm not sure which you are trying to build now.

Jut compile Espruino for the esp32 or build the ESP-idf libs?

I think it would be best to start fresh, as I don't know what state your files are in.

**Comment by jdschuitemaker** [comment]
Okay, I think I did all the steps again and it fails. I want to build
Espruino for ESP32 and possibly contribute to it.

Which steps should I follow please?

Met vriendelijke groeten, Warm regards,

Jan-Dirk Schuitemaker

**Comment by wilberforce** [comment]
@jdschuitemaker 

I have updated https://github.com/espruino/EspruinoBuildTools/blob/master/esp32/README.md

To build espruino for the ESP32 , this is all you need to do:

```
git clone https://github.com/espruino/Espruino.git
cd Espruino
source scripts/provision.sh ESP32
make clean && BOARD=ESP32 make
```

**Comment by jdschuitemaker** [comment]
Now it works. I still see a lot of warnings, but you said that is okay!

Thank you very much @wilberforce
